title = "takeokunn's blog"
baseURL = 'https://www.takeokunn.org/'

defaultContentLanguage = "ja-jp"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
theme = "hugo-take-theme"

timeZone = "Asia/Tokyo"

[params]
DateForm = "2006.1.2"
heroTitle = "takeokunn's blog"
heroSubtitle = "poem driven development"
featuredArticles = [
    "/posts/fleeting/20250722020425-proposal_guide/",
    "/posts/fleeting/20250518144557-local_git_branch_operation/",
    "/posts/fleeting/20250514155803-yubikey_gpg_operation/",
    "/posts/fleeting/20250619103829-build_cv_resume_with_typst/",
    "/posts/permanent/20240112071806-my_relationship_with_org_mode_in_2023_and_how_navigate_in_2024/",
    "/posts/permanent/20231219122351-how_to_manage_blog_by_org_roam/",
    "/posts/permanent/20221217132815-emacs_more_faster/",
    "/posts/permanent/20201003015736-most_important_thing_number_of_trials_for_newbie/"
]
featuredArticlesMoreLink = "/posts/"

[params.social]
zenn = "https://zenn.dev/takeokunn"
twitter = "https://x.com/takeokunn/"
github = "https://github.com/takeokunn"
keyoxide = "https://keyoxide.org/0B10DAA7BA0236D7382287660F79C0AB03FD7A1C"
rss = "/index.xml"

[[params.pdfLinks]]
title = "2025年5月 個人的Nixユースケース紹介"
url = "/pdf/nix-meetup-3-my-nix-usecase.pdf"
date = "2025-05-01"

[[params.pdfLinks]]
title = "Phpactorから学ぶLanguage Server Protocolの仕組み"
url = "/pdf/phperkaigi-2025-pamphlet.pdf"
date = "2025-03-01"

[[params.pdfLinks]]
title = "パッケージマネージャNixで実現する宣言的でクリーンなPHP開発環境の構築"
url = "/pdf/phperkaigi-2026-pamphlet.pdf"
date = "2026-03-01"

[[params.pdfLinks]]
title = "Software DesignでNix連載をした"
url = "/pdf/publishing-nix-series-software-design.pdf"
date = "2024-06-01"

[[params.pdfLinks]]
title = "Typstで登壇できるようになったので練習させてくれ"
url = "/pdf/typst-presentation-practice.pdf"
date = "2024-01-01"

[[params.pdfLinks]]
title = "Example Slide"
url = "/pdf/example-slide.pdf"
date = "2024-01-01"

[[params.pdfLinks]]
title = "Example Slide Light Theme"
url = "/pdf/example-slide-light-theme.pdf"
date = "2024-01-01"

[markup]
[markup.highlight]
noClasses = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[taxonomies]
tag = "tags"

[Languages.ja-jp]
languageName = "Japanese"
languageCode = "ja-jp"
contentDir = "content/"

[Languages.ja-jp.params]
mainSections = ['posts']
dateFormat = "2 May 2023"

[outputFormats]
[outputFormats.llms]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true
rel = "alternate"
root = true

[outputFormats.llmsfull]
mediaType = "text/plain"
baseName = "llms-full"
isPlainText = true
rel = "alternate"
root = true

[outputs]
home = ["HTML", "RSS", "llms", "llmsfull"]
